version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            /home/circleci/project/venv/bin/python3 -m pip install --upgrade pip
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Installing additional libraries
          command: |
            . venv/bin/activate
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pip3 install pytest
            pytest tests
      - store_artifacts:
          path: test-reports/
          destination: python_app